# Generated by Django 5.2.1 on 2025-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
